# Server Configuration
spring.application.name=travel-planner-mgt
server.port=7002

# Activate local profile
spring.profiles.active=local

server.error.include-message=always
server.error.include-binding-errors=always

# Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=6
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000

# JPA Configuration - DISABLE DDL AUTO
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
